'''
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: liquid_flow_dialects.xml

Note: this file has been auto-generated. DO NOT EDIT
'''
from __future__ import print_function
from builtins import range
from builtins import object
import struct, array, time, json, os, sys, platform

from crc import x25crc
import hashlib

WIRE_PROTOCOL_VERSION = '1.0'
DIALECT = 'liquid_flow_dialect'

PROTOCOL_MARKER_V1 = 0xFE
PROTOCOL_MARKER_V2 = 0xFD
HEADER_LEN_V1 = 6
HEADER_LEN_V2 = 10

MAVLINK_SIGNATURE_BLOCK_LEN = 13

MAVLINK_IFLAG_SIGNED = 0x01

native_supported = platform.system() != 'Windows' # Not yet supported on other dialects
native_force = 'MAVNATIVE_FORCE' in os.environ # Will force use of native code regardless of what client app wants
native_testing = 'MAVNATIVE_TESTING' in os.environ # Will force both native and legacy code to be used and their results compared

if native_supported and float(WIRE_PROTOCOL_VERSION) <= 1:
    try:
        import mavnative
    except ImportError:
        print('ERROR LOADING MAVNATIVE - falling back to python implementation')
        native_supported = False
else:
    # mavnative isn't supported for MAVLink2 yet
    native_supported = False

# allow MAV_IGNORE_CRC=1 to ignore CRC, allowing some
# corrupted msgs to be seen
MAVLINK_IGNORE_CRC = os.environ.get("MAV_IGNORE_CRC",0)

# some base types from mavlink_types.h
MAVLINK_TYPE_CHAR     = 0
MAVLINK_TYPE_UINT8_T  = 1
MAVLINK_TYPE_INT8_T   = 2
MAVLINK_TYPE_UINT16_T = 3
MAVLINK_TYPE_INT16_T  = 4
MAVLINK_TYPE_UINT32_T = 5
MAVLINK_TYPE_INT32_T  = 6
MAVLINK_TYPE_UINT64_T = 7
MAVLINK_TYPE_INT64_T  = 8
MAVLINK_TYPE_FLOAT    = 9
MAVLINK_TYPE_DOUBLE   = 10


# swiped from DFReader.py
def to_string(s):
    '''desperate attempt to convert a string regardless of what garbage we get'''
    try:
        return s.decode("utf-8")
    except Exception as e:
        pass
    try:
        s2 = s.encode('utf-8', 'ignore')
        x = u"%s" % s2
        return s2
    except Exception:
        pass
    # so its a nasty one. Let's grab as many characters as we can
    r = ''
    try:
        for c in s:
            r2 = r + c
            r2 = r2.encode('ascii', 'ignore')
            x = u"%s" % r2
            r = r2
    except Exception:
        pass
    return r + '_XXX'


class MAVLink_header(object):
    '''MAVLink message header'''
    def __init__(self, msgId, incompat_flags=0, compat_flags=0, mlen=0, seq=0, srcSystem=0, srcComponent=0):
        self.mlen = mlen
        self.seq = seq
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.msgId = msgId
        self.incompat_flags = incompat_flags
        self.compat_flags = compat_flags

    def pack(self, force_mavlink1=False):
        if WIRE_PROTOCOL_VERSION == '2.0' and not force_mavlink1:
            return struct.pack('<BBBBBBBHB', 254, self.mlen,
                               self.incompat_flags, self.compat_flags,
                               self.seq, self.srcSystem, self.srcComponent,
                               self.msgId&0xFFFF, self.msgId>>16)
        return struct.pack('<BBBBBB', PROTOCOL_MARKER_V1, self.mlen, self.seq,
                           self.srcSystem, self.srcComponent, self.msgId)

class MAVLink_message(object):
    '''base MAVLink message class'''
    def __init__(self, msgId, name):
        self._header     = MAVLink_header(msgId)
        self._payload    = None
        self._msgbuf     = None
        self._crc        = None
        self._fieldnames = []
        self._type       = name
        self._signed     = False
        self._link_id    = None
        self._instances  = None
        self._instance_field = None

    def format_attr(self, field):
        '''override field getter'''
        raw_attr = getattr(self,field)
        if isinstance(raw_attr, bytes):
            raw_attr = to_string(raw_attr).rstrip("\00")
        return raw_attr

    def get_msgbuf(self):
        if isinstance(self._msgbuf, bytearray):
            return self._msgbuf
        return bytearray(self._msgbuf)

    def get_header(self):
        return self._header

    def get_payload(self):
        return self._payload

    def get_crc(self):
        return self._crc

    def get_fieldnames(self):
        return self._fieldnames

    def get_type(self):
        return self._type

    def get_msgId(self):
        return self._header.msgId

    def get_srcSystem(self):
        return self._header.srcSystem

    def get_srcComponent(self):
        return self._header.srcComponent

    def get_seq(self):
        return self._header.seq

    def get_signed(self):
        return self._signed

    def get_link_id(self):
        return self._link_id

    def __str__(self):
        ret = '%s {' % self._type
        for a in self._fieldnames:
            v = self.format_attr(a)
            ret += '%s : %s, ' % (a, v)
        ret = ret[0:-2] + '}'
        return ret

    def __ne__(self, other):
        return not self.__eq__(other)

    def __eq__(self, other):
        if other is None:
            return False

        if self.get_type() != other.get_type():
            return False

        # We do not compare CRC because native code doesn't provide it
        #if self.get_crc() != other.get_crc():
        #    return False

        if self.get_seq() != other.get_seq():
            return False

        if self.get_srcSystem() != other.get_srcSystem():
            return False

        if self.get_srcComponent() != other.get_srcComponent():
            return False

        for a in self._fieldnames:
            if self.format_attr(a) != other.format_attr(a):
                return False

        return True

    def to_dict(self):
        d = dict({})
        d['mavpackettype'] = self._type
        for a in self._fieldnames:
          d[a] = self.format_attr(a)
        return d

    def to_json(self):
        return json.dumps(self.to_dict())

    def sign_packet(self, mav):
        h = hashlib.new('sha256')
        self._msgbuf += struct.pack('<BQ', mav.signing.link_id, mav.signing.timestamp)[:7]
        h.update(mav.signing.secret_key)
        h.update(self._msgbuf)
        sig = h.digest()[:6]
        self._msgbuf += sig
        mav.signing.timestamp += 1

    def pack(self, mav, crc_extra, payload, force_mavlink1=False):
        plen = len(payload)
        if WIRE_PROTOCOL_VERSION != '1.0' and not force_mavlink1:
            # in MAVLink2 we can strip trailing zeros off payloads. This allows for simple
            # variable length arrays and smaller packets
            nullbyte = chr(0)
            # in Python2, type("fred') is str but also type("fred")==bytes
            if str(type(payload)) == "<class 'bytes'>":
                nullbyte = 0
            while plen > 1 and payload[plen-1] == nullbyte:
                plen -= 1
        self._payload = payload[:plen]
        incompat_flags = 0
        if mav.signing.sign_outgoing:
            incompat_flags |= MAVLINK_IFLAG_SIGNED
        self._header  = MAVLink_header(self._header.msgId,
                                       incompat_flags=incompat_flags, compat_flags=0,
                                       mlen=len(self._payload), seq=mav.seq,
                                       srcSystem=mav.srcSystem, srcComponent=mav.srcComponent)
        self._msgbuf = self._header.pack(force_mavlink1=force_mavlink1) + self._payload
        crc = x25crc(self._msgbuf[1:])
        if True: # using CRC extra
            crc.accumulate_str(struct.pack('B', crc_extra))
        self._crc = crc.crc
        self._msgbuf += struct.pack('<H', self._crc)
        if mav.signing.sign_outgoing and not force_mavlink1:
            self.sign_packet(mav)
        return self._msgbuf

    def __getitem__(self, key):
        '''support indexing, allowing for multi-instance sensors in one message'''
        if self._instances is None:
            raise IndexError()
        if not key in self._instances:
            raise IndexError()
        return self._instances[key]


# enums

class EnumEntry(object):
    def __init__(self, name, description):
        self.name = name
        self.description = description
        self.param = {}

enums = {}

# SENSOR_DATA_TYPE
enums['SENSOR_DATA_TYPE'] = {}
SENSOR_DATA_TYPE_RAW = 0 # Raw uncorrected data
enums['SENSOR_DATA_TYPE'][0] = EnumEntry('SENSOR_DATA_TYPE_RAW', '''Raw uncorrected data''')
SENSOR_DATA_TYPE_FLOW = 1 # Sensor Corrected Flow data
enums['SENSOR_DATA_TYPE'][1] = EnumEntry('SENSOR_DATA_TYPE_FLOW', '''Sensor Corrected Flow data''')
SENSOR_DATA_TYPE_BOTH = 2 # Both Raw and Corrected Flow data
enums['SENSOR_DATA_TYPE'][2] = EnumEntry('SENSOR_DATA_TYPE_BOTH', '''Both Raw and Corrected Flow data''')
SENSOR_DATA_TYPE_ENUM_END = 3 # 
enums['SENSOR_DATA_TYPE'][3] = EnumEntry('SENSOR_DATA_TYPE_ENUM_END', '''''')

# message IDs
MAVLINK_MSG_ID_BAD_DATA = -1
MAVLINK_MSG_ID_WRITE_SEGMENT_COEFFS = 1
MAVLINK_MSG_ID_READ_SEGMENT_COEFFS = 2
MAVLINK_MSG_ID_RESPONSE_READ_SEGMENT_COEFFS = 51
MAVLINK_MSG_ID_CONFIGURE_DATA_STREAM = 101
MAVLINK_MSG_ID_CONFIGURE_SENSIRION_DATA_STREAM = 102
MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL = 103
MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL_DATA_STREAM = 104
MAVLINK_MSG_ID_RESPONSE_SENSOR_RAW_DATA = 151
MAVLINK_MSG_ID_RESPONSE_SENSOR_FLOW_DATA = 152
MAVLINK_MSG_ID_RESPONSE_SENSOR_BOTH_DATA = 153
MAVLINK_MSG_ID_RESPONSE_SENSIRION_DATA = 154
MAVLINK_MSG_ID_RESPONSE_HEATER_CONTROL_DATA = 171

class MAVLink_write_segment_coeffs_message(MAVLink_message):
        '''
        Write coefficients of a spline
        '''
        id = MAVLINK_MSG_ID_WRITE_SEGMENT_COEFFS
        name = 'WRITE_SEGMENT_COEFFS'
        fieldnames = ['segment_id', 'data']
        ordered_fieldnames = ['segment_id', 'data']
        fieldtypes = ['uint32_t', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<I16B'
        native_format = bytearray('<IB', 'ascii')
        orders = [0, 1]
        lengths = [1, 16]
        array_lengths = [0, 16]
        crc_extra = 173
        unpacker = struct.Struct('<I16B')
        instance_field = None
        instance_offset = -1

        def __init__(self, segment_id, data):
                MAVLink_message.__init__(self, MAVLink_write_segment_coeffs_message.id, MAVLink_write_segment_coeffs_message.name)
                self._fieldnames = MAVLink_write_segment_coeffs_message.fieldnames
                self._instance_field = MAVLink_write_segment_coeffs_message.instance_field
                self._instance_offset = MAVLink_write_segment_coeffs_message.instance_offset
                self.segment_id = segment_id
                self.data = data

        def pack(self, mav, force_mavlink1=False):
                x = struct.pack('<I16B', self.segment_id, self.data[0], self.data[1], self.data[2], self.data[3], self.data[4], self.data[5], self.data[6], self.data[7], self.data[8], self.data[9], self.data[10], self.data[11], self.data[12], self.data[13], self.data[14], self.data[15])
                y = struct.unpack('<I16B', x)
                return MAVLink_message.pack(self, mav, 173, x, force_mavlink1=force_mavlink1)

class MAVLink_read_segment_coeffs_message(MAVLink_message):
        '''
        Read coefficients of a spline
        '''
        id = MAVLINK_MSG_ID_READ_SEGMENT_COEFFS
        name = 'READ_SEGMENT_COEFFS'
        fieldnames = ['segment_id']
        ordered_fieldnames = ['segment_id']
        fieldtypes = ['uint32_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<I'
        native_format = bytearray('<I', 'ascii')
        orders = [0]
        lengths = [1]
        array_lengths = [0]
        crc_extra = 249
        unpacker = struct.Struct('<I')
        instance_field = None
        instance_offset = -1

        def __init__(self, segment_id):
                MAVLink_message.__init__(self, MAVLink_read_segment_coeffs_message.id, MAVLink_read_segment_coeffs_message.name)
                self._fieldnames = MAVLink_read_segment_coeffs_message.fieldnames
                self._instance_field = MAVLink_read_segment_coeffs_message.instance_field
                self._instance_offset = MAVLink_read_segment_coeffs_message.instance_offset
                self.segment_id = segment_id

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 249, struct.pack('<I', self.segment_id), force_mavlink1=force_mavlink1)

class MAVLink_response_read_segment_coeffs_message(MAVLink_message):
        '''
        Response for a read coefficients command
        '''
        id = MAVLINK_MSG_ID_RESPONSE_READ_SEGMENT_COEFFS
        name = 'RESPONSE_READ_SEGMENT_COEFFS'
        fieldnames = ['segment_id', 'data']
        ordered_fieldnames = ['segment_id', 'data']
        fieldtypes = ['uint32_t', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<I16B'
        native_format = bytearray('<IB', 'ascii')
        orders = [0, 1]
        lengths = [1, 16]
        array_lengths = [0, 16]
        crc_extra = 74
        unpacker = struct.Struct('<I16B')
        instance_field = None
        instance_offset = -1

        def __init__(self, segment_id, data):
                MAVLink_message.__init__(self, MAVLink_response_read_segment_coeffs_message.id, MAVLink_response_read_segment_coeffs_message.name)
                self._fieldnames = MAVLink_response_read_segment_coeffs_message.fieldnames
                self._instance_field = MAVLink_response_read_segment_coeffs_message.instance_field
                self._instance_offset = MAVLink_response_read_segment_coeffs_message.instance_offset
                self.segment_id = segment_id
                self.data = data

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 74, struct.pack('<I16B', self.segment_id, self.data[0], self.data[1], self.data[2], self.data[3], self.data[4], self.data[5], self.data[6], self.data[7], self.data[8], self.data[9], self.data[10], self.data[11], self.data[12], self.data[13], self.data[14], self.data[15]), force_mavlink1=force_mavlink1)

class MAVLink_configure_data_stream_message(MAVLink_message):
        '''
        Configure frequency to read the flow data and to initiate the
        data read
        '''
        id = MAVLINK_MSG_ID_CONFIGURE_DATA_STREAM
        name = 'CONFIGURE_DATA_STREAM'
        fieldnames = ['sensor_data_type', 'frequency']
        ordered_fieldnames = ['frequency', 'sensor_data_type']
        fieldtypes = ['uint8_t', 'uint16_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<HB'
        native_format = bytearray('<HB', 'ascii')
        orders = [1, 0]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 70
        unpacker = struct.Struct('<HB')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_data_type, frequency):
                MAVLink_message.__init__(self, MAVLink_configure_data_stream_message.id, MAVLink_configure_data_stream_message.name)
                self._fieldnames = MAVLink_configure_data_stream_message.fieldnames
                self._instance_field = MAVLink_configure_data_stream_message.instance_field
                self._instance_offset = MAVLink_configure_data_stream_message.instance_offset
                self.sensor_data_type = sensor_data_type
                self.frequency = frequency

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 70, struct.pack('<HB', self.frequency, self.sensor_data_type), force_mavlink1=force_mavlink1)

class MAVLink_configure_sensirion_data_stream_message(MAVLink_message):
        '''
        Configure sensirion data stream and to initiate the data read
        '''
        id = MAVLINK_MSG_ID_CONFIGURE_SENSIRION_DATA_STREAM
        name = 'CONFIGURE_SENSIRION_DATA_STREAM'
        fieldnames = ['sensor_data_type']
        ordered_fieldnames = ['sensor_data_type']
        fieldtypes = ['uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<B'
        native_format = bytearray('<B', 'ascii')
        orders = [0]
        lengths = [1]
        array_lengths = [0]
        crc_extra = 200
        unpacker = struct.Struct('<B')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_data_type):
                MAVLink_message.__init__(self, MAVLink_configure_sensirion_data_stream_message.id, MAVLink_configure_sensirion_data_stream_message.name)
                self._fieldnames = MAVLink_configure_sensirion_data_stream_message.fieldnames
                self._instance_field = MAVLink_configure_sensirion_data_stream_message.instance_field
                self._instance_offset = MAVLink_configure_sensirion_data_stream_message.instance_offset
                self.sensor_data_type = sensor_data_type

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 200, struct.pack('<B', self.sensor_data_type), force_mavlink1=force_mavlink1)

class MAVLink_configure_heater_control_message(MAVLink_message):
        '''
        Configure heater control parameters
        '''
        id = MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL
        name = 'CONFIGURE_HEATER_CONTROL'
        fieldnames = ['heater_control_type', 'heater_control_frequency', 'target_heater_voltage', 'max_heater_voltage', 'heater_voltage_tolerance', 'pid_gains', 'heater_current_range', 'rt_current_range']
        ordered_fieldnames = ['target_heater_voltage', 'max_heater_voltage', 'heater_voltage_tolerance', 'pid_gains', 'heater_control_frequency', 'heater_control_type', 'heater_current_range', 'rt_current_range']
        fieldtypes = ['uint8_t', 'uint16_t', 'float', 'float', 'float', 'float', 'uint8_t', 'uint8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<fff3fHBBB'
        native_format = bytearray('<ffffHBBB', 'ascii')
        orders = [5, 4, 0, 1, 2, 3, 6, 7]
        lengths = [1, 1, 1, 3, 1, 1, 1, 1]
        array_lengths = [0, 0, 0, 3, 0, 0, 0, 0]
        crc_extra = 118
        unpacker = struct.Struct('<fff3fHBBB')
        instance_field = None
        instance_offset = -1

        def __init__(self, heater_control_type, heater_control_frequency, target_heater_voltage, max_heater_voltage, heater_voltage_tolerance, pid_gains, heater_current_range, rt_current_range):
                MAVLink_message.__init__(self, MAVLink_configure_heater_control_message.id, MAVLink_configure_heater_control_message.name)
                self._fieldnames = MAVLink_configure_heater_control_message.fieldnames
                self._instance_field = MAVLink_configure_heater_control_message.instance_field
                self._instance_offset = MAVLink_configure_heater_control_message.instance_offset
                self.heater_control_type = heater_control_type
                self.heater_control_frequency = heater_control_frequency
                self.target_heater_voltage = target_heater_voltage
                self.max_heater_voltage = max_heater_voltage
                self.heater_voltage_tolerance = heater_voltage_tolerance
                self.pid_gains = pid_gains
                self.heater_current_range = heater_current_range
                self.rt_current_range = rt_current_range

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 118, struct.pack('<fff3fHBBB', self.target_heater_voltage, self.max_heater_voltage, self.heater_voltage_tolerance, self.pid_gains[0], self.pid_gains[1], self.pid_gains[2], self.heater_control_frequency, self.heater_control_type, self.heater_current_range, self.rt_current_range), force_mavlink1=force_mavlink1)

class MAVLink_configure_heater_control_data_stream_message(MAVLink_message):
        '''
        Configure frequency to read heater control data and to
        initiate the data read
        '''
        id = MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL_DATA_STREAM
        name = 'CONFIGURE_HEATER_CONTROL_DATA_STREAM'
        fieldnames = ['data_type', 'data_stream_frequency']
        ordered_fieldnames = ['data_stream_frequency', 'data_type']
        fieldtypes = ['uint8_t', 'uint16_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<HB'
        native_format = bytearray('<HB', 'ascii')
        orders = [1, 0]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 206
        unpacker = struct.Struct('<HB')
        instance_field = None
        instance_offset = -1

        def __init__(self, data_type, data_stream_frequency):
                MAVLink_message.__init__(self, MAVLink_configure_heater_control_data_stream_message.id, MAVLink_configure_heater_control_data_stream_message.name)
                self._fieldnames = MAVLink_configure_heater_control_data_stream_message.fieldnames
                self._instance_field = MAVLink_configure_heater_control_data_stream_message.instance_field
                self._instance_offset = MAVLink_configure_heater_control_data_stream_message.instance_offset
                self.data_type = data_type
                self.data_stream_frequency = data_stream_frequency

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 206, struct.pack('<HB', self.data_stream_frequency, self.data_type), force_mavlink1=force_mavlink1)

class MAVLink_response_sensor_raw_data_message(MAVLink_message):
        '''
        Sensor raw and temperature data
        '''
        id = MAVLINK_MSG_ID_RESPONSE_SENSOR_RAW_DATA
        name = 'RESPONSE_SENSOR_RAW_DATA'
        fieldnames = ['sensor_raw_data', 'sensor_temperature_data']
        ordered_fieldnames = ['sensor_raw_data', 'sensor_temperature_data']
        fieldtypes = ['int32_t', 'int32_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<ii'
        native_format = bytearray('<ii', 'ascii')
        orders = [0, 1]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 107
        unpacker = struct.Struct('<ii')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_raw_data, sensor_temperature_data):
                MAVLink_message.__init__(self, MAVLink_response_sensor_raw_data_message.id, MAVLink_response_sensor_raw_data_message.name)
                self._fieldnames = MAVLink_response_sensor_raw_data_message.fieldnames
                self._instance_field = MAVLink_response_sensor_raw_data_message.instance_field
                self._instance_offset = MAVLink_response_sensor_raw_data_message.instance_offset
                self.sensor_raw_data = sensor_raw_data
                self.sensor_temperature_data = sensor_temperature_data

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 107, struct.pack('<ii', self.sensor_raw_data, self.sensor_temperature_data), force_mavlink1=force_mavlink1)

class MAVLink_response_sensor_flow_data_message(MAVLink_message):
        '''
        Sensor corrected data and temperature data
        '''
        id = MAVLINK_MSG_ID_RESPONSE_SENSOR_FLOW_DATA
        name = 'RESPONSE_SENSOR_FLOW_DATA'
        fieldnames = ['sensor_flow_data', 'sensor_temperature_data']
        ordered_fieldnames = ['sensor_flow_data', 'sensor_temperature_data']
        fieldtypes = ['int32_t', 'int32_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<ii'
        native_format = bytearray('<ii', 'ascii')
        orders = [0, 1]
        lengths = [1, 1]
        array_lengths = [0, 0]
        crc_extra = 37
        unpacker = struct.Struct('<ii')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_flow_data, sensor_temperature_data):
                MAVLink_message.__init__(self, MAVLink_response_sensor_flow_data_message.id, MAVLink_response_sensor_flow_data_message.name)
                self._fieldnames = MAVLink_response_sensor_flow_data_message.fieldnames
                self._instance_field = MAVLink_response_sensor_flow_data_message.instance_field
                self._instance_offset = MAVLink_response_sensor_flow_data_message.instance_offset
                self.sensor_flow_data = sensor_flow_data
                self.sensor_temperature_data = sensor_temperature_data

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 37, struct.pack('<ii', self.sensor_flow_data, self.sensor_temperature_data), force_mavlink1=force_mavlink1)

class MAVLink_response_sensor_both_data_message(MAVLink_message):
        '''
        Sensor raw data, corrected data and temperature data
        '''
        id = MAVLINK_MSG_ID_RESPONSE_SENSOR_BOTH_DATA
        name = 'RESPONSE_SENSOR_BOTH_DATA'
        fieldnames = ['sensor_flow_data', 'sensor_raw_data', 'sensor_temperature_data']
        ordered_fieldnames = ['sensor_flow_data', 'sensor_raw_data', 'sensor_temperature_data']
        fieldtypes = ['int32_t', 'int32_t', 'int32_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<iii'
        native_format = bytearray('<iii', 'ascii')
        orders = [0, 1, 2]
        lengths = [1, 1, 1]
        array_lengths = [0, 0, 0]
        crc_extra = 215
        unpacker = struct.Struct('<iii')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_flow_data, sensor_raw_data, sensor_temperature_data):
                MAVLink_message.__init__(self, MAVLink_response_sensor_both_data_message.id, MAVLink_response_sensor_both_data_message.name)
                self._fieldnames = MAVLink_response_sensor_both_data_message.fieldnames
                self._instance_field = MAVLink_response_sensor_both_data_message.instance_field
                self._instance_offset = MAVLink_response_sensor_both_data_message.instance_offset
                self.sensor_flow_data = sensor_flow_data
                self.sensor_raw_data = sensor_raw_data
                self.sensor_temperature_data = sensor_temperature_data

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 215, struct.pack('<iii', self.sensor_flow_data, self.sensor_raw_data, self.sensor_temperature_data), force_mavlink1=force_mavlink1)

class MAVLink_response_sensirion_data_message(MAVLink_message):
        '''
        Sensirion data
        '''
        id = MAVLINK_MSG_ID_RESPONSE_SENSIRION_DATA
        name = 'RESPONSE_SENSIRION_DATA'
        fieldnames = ['sensor_flow_data', 'sensor_temp_data', 'sensor_status_data']
        ordered_fieldnames = ['sensor_flow_data', 'sensor_temp_data', 'sensor_status_data']
        fieldtypes = ['int16_t', 'int16_t', 'int8_t']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<hhb'
        native_format = bytearray('<hhb', 'ascii')
        orders = [0, 1, 2]
        lengths = [1, 1, 1]
        array_lengths = [0, 0, 0]
        crc_extra = 6
        unpacker = struct.Struct('<hhb')
        instance_field = None
        instance_offset = -1

        def __init__(self, sensor_flow_data, sensor_temp_data, sensor_status_data):
                MAVLink_message.__init__(self, MAVLink_response_sensirion_data_message.id, MAVLink_response_sensirion_data_message.name)
                self._fieldnames = MAVLink_response_sensirion_data_message.fieldnames
                self._instance_field = MAVLink_response_sensirion_data_message.instance_field
                self._instance_offset = MAVLink_response_sensirion_data_message.instance_offset
                self.sensor_flow_data = sensor_flow_data
                self.sensor_temp_data = sensor_temp_data
                self.sensor_status_data = sensor_status_data

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 6, struct.pack('<hhb', self.sensor_flow_data, self.sensor_temp_data, self.sensor_status_data), force_mavlink1=force_mavlink1)

class MAVLink_response_heater_control_data_message(MAVLink_message):
        '''
        Heater control data
        '''
        id = MAVLINK_MSG_ID_RESPONSE_HEATER_CONTROL_DATA
        name = 'RESPONSE_HEATER_CONTROL_DATA'
        fieldnames = ['v_h', 'v_t', 'i_h', 'i_t', 'v_drop_t']
        ordered_fieldnames = ['v_h', 'v_t', 'i_h', 'i_t', 'v_drop_t']
        fieldtypes = ['float', 'float', 'float', 'float', 'float']
        fielddisplays_by_name = {}
        fieldenums_by_name = {}
        fieldunits_by_name = {}
        format = '<fffff'
        native_format = bytearray('<fffff', 'ascii')
        orders = [0, 1, 2, 3, 4]
        lengths = [1, 1, 1, 1, 1]
        array_lengths = [0, 0, 0, 0, 0]
        crc_extra = 115
        unpacker = struct.Struct('<fffff')
        instance_field = None
        instance_offset = -1

        def __init__(self, v_h, v_t, i_h, i_t, v_drop_t):
                MAVLink_message.__init__(self, MAVLink_response_heater_control_data_message.id, MAVLink_response_heater_control_data_message.name)
                self._fieldnames = MAVLink_response_heater_control_data_message.fieldnames
                self._instance_field = MAVLink_response_heater_control_data_message.instance_field
                self._instance_offset = MAVLink_response_heater_control_data_message.instance_offset
                self.v_h = v_h
                self.v_t = v_t
                self.i_h = i_h
                self.i_t = i_t
                self.v_drop_t = v_drop_t

        def pack(self, mav, force_mavlink1=False):
                return MAVLink_message.pack(self, mav, 115, struct.pack('<fffff', self.v_h, self.v_t, self.i_h, self.i_t, self.v_drop_t), force_mavlink1=force_mavlink1)


mavlink_map = {
        MAVLINK_MSG_ID_WRITE_SEGMENT_COEFFS : MAVLink_write_segment_coeffs_message,
        MAVLINK_MSG_ID_READ_SEGMENT_COEFFS : MAVLink_read_segment_coeffs_message,
        MAVLINK_MSG_ID_RESPONSE_READ_SEGMENT_COEFFS : MAVLink_response_read_segment_coeffs_message,
        MAVLINK_MSG_ID_CONFIGURE_DATA_STREAM : MAVLink_configure_data_stream_message,
        MAVLINK_MSG_ID_CONFIGURE_SENSIRION_DATA_STREAM : MAVLink_configure_sensirion_data_stream_message,
        MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL : MAVLink_configure_heater_control_message,
        MAVLINK_MSG_ID_CONFIGURE_HEATER_CONTROL_DATA_STREAM : MAVLink_configure_heater_control_data_stream_message,
        MAVLINK_MSG_ID_RESPONSE_SENSOR_RAW_DATA : MAVLink_response_sensor_raw_data_message,
        MAVLINK_MSG_ID_RESPONSE_SENSOR_FLOW_DATA : MAVLink_response_sensor_flow_data_message,
        MAVLINK_MSG_ID_RESPONSE_SENSOR_BOTH_DATA : MAVLink_response_sensor_both_data_message,
        MAVLINK_MSG_ID_RESPONSE_SENSIRION_DATA : MAVLink_response_sensirion_data_message,
        MAVLINK_MSG_ID_RESPONSE_HEATER_CONTROL_DATA : MAVLink_response_heater_control_data_message,
}

class MAVError(Exception):
        '''MAVLink error class'''
        def __init__(self, msg):
            Exception.__init__(self, msg)
            self.message = msg

class MAVString(str):
        '''NUL terminated string'''
        def __init__(self, s):
                str.__init__(self)
        def __str__(self):
            i = self.find(chr(0))
            if i == -1:
                return self[:]
            return self[0:i]

class MAVLink_bad_data(MAVLink_message):
        '''
        a piece of bad data in a mavlink stream
        '''
        def __init__(self, data, reason):
                MAVLink_message.__init__(self, MAVLINK_MSG_ID_BAD_DATA, 'BAD_DATA')
                self._fieldnames = ['data', 'reason']
                self.data = data
                self.reason = reason
                self._msgbuf = data
                self._instance_field = None

        def __str__(self):
            '''Override the __str__ function from MAVLink_messages because non-printable characters are common in to be the reason for this message to exist.'''
            return '%s {%s, data:%s}' % (self._type, self.reason, [('%x' % ord(i) if isinstance(i, str) else '%x' % i) for i in self.data])

class MAVLinkSigning(object):
    '''MAVLink signing state class'''
    def __init__(self):
        self.secret_key = None
        self.timestamp = 0
        self.link_id = 0
        self.sign_outgoing = False
        self.allow_unsigned_callback = None
        self.stream_timestamps = {}
        self.sig_count = 0
        self.badsig_count = 0
        self.goodsig_count = 0
        self.unsigned_count = 0
        self.reject_count = 0

class MAVLink(object):
        '''MAVLink protocol handling class'''
        def __init__(self, file, srcSystem=0, srcComponent=0, use_native=False):
                self.seq = 0
                self.file = file
                self.srcSystem = srcSystem
                self.srcComponent = srcComponent
                self.callback = None
                self.callback_args = None
                self.callback_kwargs = None
                self.send_callback = None
                self.send_callback_args = None
                self.send_callback_kwargs = None
                self.buf = bytearray()
                self.buf_index = 0
                self.expected_length = HEADER_LEN_V1+2
                self.have_prefix_error = False
                self.robust_parsing = False
                self.protocol_marker = 254
                self.little_endian = True
                self.crc_extra = True
                self.sort_fields = True
                self.total_packets_sent = 0
                self.total_bytes_sent = 0
                self.total_packets_received = 0
                self.total_bytes_received = 0
                self.total_receive_errors = 0
                self.startup_time = time.time()
                self.signing = MAVLinkSigning()
                if native_supported and (use_native or native_testing or native_force):
                    print("NOTE: mavnative is currently beta-test code")
                    self.native = mavnative.NativeConnection(MAVLink_message, mavlink_map)
                else:
                    self.native = None
                if native_testing:
                    self.test_buf = bytearray()
                self.mav20_unpacker = struct.Struct('<cBBBBBBHB')
                self.mav10_unpacker = struct.Struct('<cBBBBB')
                self.mav20_h3_unpacker = struct.Struct('BBB')
                self.mav_csum_unpacker = struct.Struct('<H')
                self.mav_sign_unpacker = struct.Struct('<IH')

        def set_callback(self, callback, *args, **kwargs):
            self.callback = callback
            self.callback_args = args
            self.callback_kwargs = kwargs

        def set_send_callback(self, callback, *args, **kwargs):
            self.send_callback = callback
            self.send_callback_args = args
            self.send_callback_kwargs = kwargs

        def send(self, mavmsg, force_mavlink1=False):
                '''send a MAVLink message'''
                buf = mavmsg.pack(self, force_mavlink1=force_mavlink1)
                self.file.write(buf)
                self.seq = (self.seq + 1) % 256
                self.total_packets_sent += 1
                self.total_bytes_sent += len(buf)
                if self.send_callback:
                    self.send_callback(mavmsg, *self.send_callback_args, **self.send_callback_kwargs)

        def buf_len(self):
            return len(self.buf) - self.buf_index

        def bytes_needed(self):
            '''return number of bytes needed for next parsing stage'''
            if self.native:
                ret = self.native.expected_length - self.buf_len()
            else:
                ret = self.expected_length - self.buf_len()

            if ret <= 0:
                return 1
            return ret

        def __parse_char_native(self, c):
            '''this method exists only to see in profiling results'''
            m = self.native.parse_chars(c)
            return m

        def __callbacks(self, msg):
            '''this method exists only to make profiling results easier to read'''
            if self.callback:
                self.callback(msg, *self.callback_args, **self.callback_kwargs)

        def parse_char(self, c):
            '''input some data bytes, possibly returning a new message'''
            self.buf.extend(c)

            self.total_bytes_received += len(c)

            if self.native:
                if native_testing:
                    self.test_buf.extend(c)
                    m = self.__parse_char_native(self.test_buf)
                    m2 = self.__parse_char_legacy()
                    if m2 != m:
                        print("Native: %s\nLegacy: %s\n" % (m, m2))
                        raise Exception('Native vs. Legacy mismatch')
                else:
                    m = self.__parse_char_native(self.buf)
            else:
                m = self.__parse_char_legacy()

            if m is not None:
                self.total_packets_received += 1
                self.__callbacks(m)
            else:
                # XXX The idea here is if we've read something and there's nothing left in
                # the buffer, reset it to 0 which frees the memory
                if self.buf_len() == 0 and self.buf_index != 0:
                    self.buf = bytearray()
                    self.buf_index = 0

            return m

        def __parse_char_legacy(self):
            '''input some data bytes, possibly returning a new message (uses no native code)'''
            header_len = HEADER_LEN_V1
            if self.buf_len() >= 1 and self.buf[self.buf_index] == PROTOCOL_MARKER_V2:
                header_len = HEADER_LEN_V2

            if self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
                magic = self.buf[self.buf_index]
                self.buf_index += 1
                if self.robust_parsing:
                    m = MAVLink_bad_data(bytearray([magic]), 'Bad prefix')
                    self.expected_length = header_len+2
                    self.total_receive_errors += 1
                    return m
                if self.have_prefix_error:
                    return None
                self.have_prefix_error = True
                self.total_receive_errors += 1
                raise MAVError("invalid MAVLink prefix '%s'" % magic)
            self.have_prefix_error = False
            if self.buf_len() >= 3:
                sbuf = self.buf[self.buf_index:3+self.buf_index]
                if sys.version_info.major < 3:
                    sbuf = str(sbuf)
                (magic, self.expected_length, incompat_flags) = self.mav20_h3_unpacker.unpack(sbuf)
                if magic == PROTOCOL_MARKER_V2 and (incompat_flags & MAVLINK_IFLAG_SIGNED):
                        self.expected_length += MAVLINK_SIGNATURE_BLOCK_LEN
                self.expected_length += header_len + 2
            if self.expected_length >= (header_len+2) and self.buf_len() >= self.expected_length:
                mbuf = array.array('B', self.buf[self.buf_index:self.buf_index+self.expected_length])
                self.buf_index += self.expected_length
                self.expected_length = header_len+2
                if self.robust_parsing:
                    try:
                        if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                            raise MAVError('invalid incompat_flags 0x%x 0x%x %u' % (incompat_flags, magic, self.expected_length))
                        m = self.decode(mbuf)
                    except MAVError as reason:
                        m = MAVLink_bad_data(mbuf, reason.message)
                        self.total_receive_errors += 1
                else:
                    if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                        raise MAVError('invalid incompat_flags 0x%x 0x%x %u' % (incompat_flags, magic, self.expected_length))
                    m = self.decode(mbuf)
                return m
            return None

        def parse_buffer(self, s):
            '''input some data bytes, possibly returning a list of new messages'''
            m = self.parse_char(s)
            if m is None:
                return None
            ret = [m]
            while True:
                m = self.parse_char("")
                if m is None:
                    return ret
                ret.append(m)
            return ret

        def check_signature(self, msgbuf, srcSystem, srcComponent):
            '''check signature on incoming message'''
            if isinstance(msgbuf, array.array):
                msgbuf = msgbuf.tostring()
            timestamp_buf = msgbuf[-12:-6]
            link_id = msgbuf[-13]
            (tlow, thigh) = self.mav_sign_unpacker.unpack(timestamp_buf)
            timestamp = tlow + (thigh<<32)

            # see if the timestamp is acceptable
            stream_key = (link_id,srcSystem,srcComponent)
            if stream_key in self.signing.stream_timestamps:
                if timestamp <= self.signing.stream_timestamps[stream_key]:
                    # reject old timestamp
                    # print('old timestamp')
                    return False
            else:
                # a new stream has appeared. Accept the timestamp if it is at most
                # one minute behind our current timestamp
                if timestamp + 6000*1000 < self.signing.timestamp:
                    # print('bad new stream ', timestamp/(100.0*1000*60*60*24*365), self.signing.timestamp/(100.0*1000*60*60*24*365))
                    return False
                self.signing.stream_timestamps[stream_key] = timestamp
                # print('new stream')

            h = hashlib.new('sha256')
            h.update(self.signing.secret_key)
            h.update(msgbuf[:-6])
            if str(type(msgbuf)) == "<class 'bytes'>" or str(type(msgbuf)) == "<class 'bytearray'>":
                # Python 3
                sig1 = h.digest()[:6]
                sig2 = msgbuf[-6:]
            else:
                sig1 = str(h.digest())[:6]
                sig2 = str(msgbuf)[-6:]
            if sig1 != sig2:
                # print('sig mismatch')
                return False

            # the timestamp we next send with is the max of the received timestamp and
            # our current timestamp
            self.signing.timestamp = max(self.signing.timestamp, timestamp)
            return True

        def decode(self, msgbuf):
                '''decode a buffer as a MAVLink message'''
                # decode the header
                if msgbuf[0] != PROTOCOL_MARKER_V1:
                    headerlen = 10
                    try:
                        magic, mlen, incompat_flags, compat_flags, seq, srcSystem, srcComponent, msgIdlow, msgIdhigh = self.mav20_unpacker.unpack(msgbuf[:headerlen])
                    except struct.error as emsg:
                        raise MAVError('Unable to unpack MAVLink header: %s' % emsg)
                    msgId = msgIdlow | (msgIdhigh<<16)
                    mapkey = msgId
                else:
                    headerlen = 6
                    try:
                        magic, mlen, seq, srcSystem, srcComponent, msgId = self.mav10_unpacker.unpack(msgbuf[:headerlen])
                        incompat_flags = 0
                        compat_flags = 0
                    except struct.error as emsg:
                        raise MAVError('Unable to unpack MAVLink header: %s' % emsg)
                    mapkey = msgId
                if (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
                    signature_len = MAVLINK_SIGNATURE_BLOCK_LEN
                else:
                    signature_len = 0

                if ord(magic) != PROTOCOL_MARKER_V1 and ord(magic) != PROTOCOL_MARKER_V2:
                    raise MAVError("invalid MAVLink prefix '%s'" % magic)
                if mlen != len(msgbuf)-(headerlen+2+signature_len):
                    raise MAVError('invalid MAVLink message length. Got %u expected %u, msgId=%u headerlen=%u' % (len(msgbuf)-(headerlen+2+signature_len), mlen, msgId, headerlen))

                if not mapkey in mavlink_map:
                    raise MAVError('unknown MAVLink message ID %s' % str(mapkey))

                # decode the payload
                type = mavlink_map[mapkey]
                fmt = type.format
                order_map = type.orders
                len_map = type.lengths
                crc_extra = type.crc_extra

                # decode the checksum
                try:
                    crc, = self.mav_csum_unpacker.unpack(msgbuf[-(2+signature_len):][:2])
                except struct.error as emsg:
                    raise MAVError('Unable to unpack MAVLink CRC: %s' % emsg)
                crcbuf = msgbuf[1:-(2+signature_len)]
                if True: # using CRC extra
                    crcbuf.append(crc_extra)
                crc2 = x25crc(crcbuf)
                if crc != crc2.crc and not MAVLINK_IGNORE_CRC:
                    raise MAVError('invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x' % (msgId, crc, crc2.crc))

                sig_ok = False
                if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                    self.signing.sig_count += 1
                if self.signing.secret_key is not None:
                    accept_signature = False
                    if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                        sig_ok = self.check_signature(msgbuf, srcSystem, srcComponent)
                        accept_signature = sig_ok
                        if sig_ok:
                            self.signing.goodsig_count += 1
                        else:
                            self.signing.badsig_count += 1
                        if not accept_signature and self.signing.allow_unsigned_callback is not None:
                            accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                            if accept_signature:
                                self.signing.unsigned_count += 1
                            else:
                                self.signing.reject_count += 1
                    elif self.signing.allow_unsigned_callback is not None:
                        accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                        if accept_signature:
                            self.signing.unsigned_count += 1
                        else:
                            self.signing.reject_count += 1
                    if not accept_signature:
                        raise MAVError('Invalid signature')

                csize = type.unpacker.size
                mbuf = msgbuf[headerlen:-(2+signature_len)]
                if len(mbuf) < csize:
                    # zero pad to give right size
                    mbuf.extend([0]*(csize - len(mbuf)))
                if len(mbuf) < csize:
                    raise MAVError('Bad message of type %s length %u needs %s' % (
                        type, len(mbuf), csize))
                mbuf = mbuf[:csize]
                try:
                    t = type.unpacker.unpack(mbuf)
                except struct.error as emsg:
                    raise MAVError('Unable to unpack MAVLink payload type=%s fmt=%s payloadLength=%u: %s' % (
                        type, fmt, len(mbuf), emsg))

                tlist = list(t)
                # handle sorted fields
                if True:
                    t = tlist[:]
                    if sum(len_map) == len(len_map):
                        # message has no arrays in it
                        for i in range(0, len(tlist)):
                            tlist[i] = t[order_map[i]]
                    else:
                        # message has some arrays
                        tlist = []
                        for i in range(0, len(order_map)):
                            order = order_map[i]
                            L = len_map[order]
                            tip = sum(len_map[:order])
                            field = t[tip]
                            if L == 1 or isinstance(field, str):
                                tlist.append(field)
                            else:
                                tlist.append(t[tip:(tip + L)])

                # terminate any strings
                for i in range(0, len(tlist)):
                    if type.fieldtypes[i] == 'char':
                        if sys.version_info.major >= 3:
                            tlist[i] = to_string(tlist[i])
                        tlist[i] = str(MAVString(tlist[i]))
                t = tuple(tlist)
                # construct the message object
                try:
                    m = type(*t)
                except Exception as emsg:
                    raise MAVError('Unable to instantiate MAVLink message of type %s : %s' % (type, emsg))
                m._signed = sig_ok
                if m._signed:
                    m._link_id = msgbuf[-13]
                m._msgbuf = msgbuf
                m._payload = msgbuf[6:-(2+signature_len)]
                m._crc = crc
                m._header = MAVLink_header(msgId, incompat_flags, compat_flags, mlen, seq, srcSystem, srcComponent)
                return m
        def write_segment_coeffs_encode(self, segment_id, data):
                '''
                Write coefficients of a spline

                segment_id                : ID of the segment to be written (type:uint32_t)
                data                      : 4 float coefficients (type:uint8_t)

                '''
                return MAVLink_write_segment_coeffs_message(segment_id, data)

        def write_segment_coeffs_send(self, segment_id, data, force_mavlink1=False):
                '''
                Write coefficients of a spline

                segment_id                : ID of the segment to be written (type:uint32_t)
                data                      : 4 float coefficients (type:uint8_t)

                '''
                return self.send(self.write_segment_coeffs_encode(segment_id, data), force_mavlink1=force_mavlink1)

        def read_segment_coeffs_encode(self, segment_id):
                '''
                Read coefficients of a spline

                segment_id                : ID of the segment to be read (type:uint32_t)

                '''
                return MAVLink_read_segment_coeffs_message(segment_id)

        def read_segment_coeffs_send(self, segment_id, force_mavlink1=False):
                '''
                Read coefficients of a spline

                segment_id                : ID of the segment to be read (type:uint32_t)

                '''
                return self.send(self.read_segment_coeffs_encode(segment_id), force_mavlink1=force_mavlink1)

        def response_read_segment_coeffs_encode(self, segment_id, data):
                '''
                Response for a read coefficients command

                segment_id                : ID of the segment (type:uint32_t)
                data                      : 4 float coefficients (type:uint8_t)

                '''
                return MAVLink_response_read_segment_coeffs_message(segment_id, data)

        def response_read_segment_coeffs_send(self, segment_id, data, force_mavlink1=False):
                '''
                Response for a read coefficients command

                segment_id                : ID of the segment (type:uint32_t)
                data                      : 4 float coefficients (type:uint8_t)

                '''
                return self.send(self.response_read_segment_coeffs_encode(segment_id, data), force_mavlink1=force_mavlink1)

        def configure_data_stream_encode(self, sensor_data_type, frequency):
                '''
                Configure frequency to read the flow data and to initiate the data
                read

                sensor_data_type          : Type of sensor data to be streamed (type:uint8_t)
                frequency                 : Frequency to read the data from sensor (type:uint16_t)

                '''
                return MAVLink_configure_data_stream_message(sensor_data_type, frequency)

        def configure_data_stream_send(self, sensor_data_type, frequency, force_mavlink1=False):
                '''
                Configure frequency to read the flow data and to initiate the data
                read

                sensor_data_type          : Type of sensor data to be streamed (type:uint8_t)
                frequency                 : Frequency to read the data from sensor (type:uint16_t)

                '''
                return self.send(self.configure_data_stream_encode(sensor_data_type, frequency), force_mavlink1=force_mavlink1)

        def configure_sensirion_data_stream_encode(self, sensor_data_type):
                '''
                Configure sensirion data stream and to initiate the data read

                sensor_data_type          : Type of sensor data to be streamed (type:uint8_t)

                '''
                return MAVLink_configure_sensirion_data_stream_message(sensor_data_type)

        def configure_sensirion_data_stream_send(self, sensor_data_type, force_mavlink1=False):
                '''
                Configure sensirion data stream and to initiate the data read

                sensor_data_type          : Type of sensor data to be streamed (type:uint8_t)

                '''
                return self.send(self.configure_sensirion_data_stream_encode(sensor_data_type), force_mavlink1=force_mavlink1)

        def configure_heater_control_encode(self, heater_control_type, heater_control_frequency, target_heater_voltage, max_heater_voltage, heater_voltage_tolerance, pid_gains, heater_current_range, rt_current_range):
                '''
                Configure heater control parameters

                heater_control_type        : Type of heater control system algorithm (type:uint8_t)
                heater_control_frequency        : Frequency of heater control loop (type:uint16_t)
                target_heater_voltage        : Target heater voltage (type:float)
                max_heater_voltage        : Heater over-voltage protection limit (type:float)
                heater_voltage_tolerance        : Acceptable tolerance in heater voltage tracking (type:float)
                pid_gains                 : Kp Ki Kd for PID control (type:float)
                heater_current_range        : Range of heater channel of Current DAC (type:uint8_t)
                rt_current_range          : Range of rt channel of current DAC (type:uint8_t)

                '''
                return MAVLink_configure_heater_control_message(heater_control_type, heater_control_frequency, target_heater_voltage, max_heater_voltage, heater_voltage_tolerance, pid_gains, heater_current_range, rt_current_range)

        def configure_heater_control_send(self, heater_control_type, heater_control_frequency, target_heater_voltage, max_heater_voltage, heater_voltage_tolerance, pid_gains, heater_current_range, rt_current_range, force_mavlink1=False):
                '''
                Configure heater control parameters

                heater_control_type        : Type of heater control system algorithm (type:uint8_t)
                heater_control_frequency        : Frequency of heater control loop (type:uint16_t)
                target_heater_voltage        : Target heater voltage (type:float)
                max_heater_voltage        : Heater over-voltage protection limit (type:float)
                heater_voltage_tolerance        : Acceptable tolerance in heater voltage tracking (type:float)
                pid_gains                 : Kp Ki Kd for PID control (type:float)
                heater_current_range        : Range of heater channel of Current DAC (type:uint8_t)
                rt_current_range          : Range of rt channel of current DAC (type:uint8_t)

                '''
                return self.send(self.configure_heater_control_encode(heater_control_type, heater_control_frequency, target_heater_voltage, max_heater_voltage, heater_voltage_tolerance, pid_gains, heater_current_range, rt_current_range), force_mavlink1=force_mavlink1)

        def configure_heater_control_data_stream_encode(self, data_type, data_stream_frequency):
                '''
                Configure frequency to read heater control data and to initiate the
                data read

                data_type                 : Type of heater control data to be streamed (type:uint8_t)
                data_stream_frequency        : Frequency to read the data (type:uint16_t)

                '''
                return MAVLink_configure_heater_control_data_stream_message(data_type, data_stream_frequency)

        def configure_heater_control_data_stream_send(self, data_type, data_stream_frequency, force_mavlink1=False):
                '''
                Configure frequency to read heater control data and to initiate the
                data read

                data_type                 : Type of heater control data to be streamed (type:uint8_t)
                data_stream_frequency        : Frequency to read the data (type:uint16_t)

                '''
                return self.send(self.configure_heater_control_data_stream_encode(data_type, data_stream_frequency), force_mavlink1=force_mavlink1)

        def response_sensor_raw_data_encode(self, sensor_raw_data, sensor_temperature_data):
                '''
                Sensor raw and temperature data

                sensor_raw_data           : Raw Sensor data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return MAVLink_response_sensor_raw_data_message(sensor_raw_data, sensor_temperature_data)

        def response_sensor_raw_data_send(self, sensor_raw_data, sensor_temperature_data, force_mavlink1=False):
                '''
                Sensor raw and temperature data

                sensor_raw_data           : Raw Sensor data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return self.send(self.response_sensor_raw_data_encode(sensor_raw_data, sensor_temperature_data), force_mavlink1=force_mavlink1)

        def response_sensor_flow_data_encode(self, sensor_flow_data, sensor_temperature_data):
                '''
                Sensor corrected data and temperature data

                sensor_flow_data          : Sensor Corrected Flow data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return MAVLink_response_sensor_flow_data_message(sensor_flow_data, sensor_temperature_data)

        def response_sensor_flow_data_send(self, sensor_flow_data, sensor_temperature_data, force_mavlink1=False):
                '''
                Sensor corrected data and temperature data

                sensor_flow_data          : Sensor Corrected Flow data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return self.send(self.response_sensor_flow_data_encode(sensor_flow_data, sensor_temperature_data), force_mavlink1=force_mavlink1)

        def response_sensor_both_data_encode(self, sensor_flow_data, sensor_raw_data, sensor_temperature_data):
                '''
                Sensor raw data, corrected data and temperature data

                sensor_flow_data          : Sensor Corrected Flow data (type:int32_t)
                sensor_raw_data           : Raw Sensor data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return MAVLink_response_sensor_both_data_message(sensor_flow_data, sensor_raw_data, sensor_temperature_data)

        def response_sensor_both_data_send(self, sensor_flow_data, sensor_raw_data, sensor_temperature_data, force_mavlink1=False):
                '''
                Sensor raw data, corrected data and temperature data

                sensor_flow_data          : Sensor Corrected Flow data (type:int32_t)
                sensor_raw_data           : Raw Sensor data (type:int32_t)
                sensor_temperature_data        : Sensor Temperature data (type:int32_t)

                '''
                return self.send(self.response_sensor_both_data_encode(sensor_flow_data, sensor_raw_data, sensor_temperature_data), force_mavlink1=force_mavlink1)

        def response_sensirion_data_encode(self, sensor_flow_data, sensor_temp_data, sensor_status_data):
                '''
                Sensirion data

                sensor_flow_data          : Sensor Corrected Flow data (type:int16_t)
                sensor_temp_data          : Sensor Temperature data (type:int16_t)
                sensor_status_data        : Sensor Status (type:int8_t)

                '''
                return MAVLink_response_sensirion_data_message(sensor_flow_data, sensor_temp_data, sensor_status_data)

        def response_sensirion_data_send(self, sensor_flow_data, sensor_temp_data, sensor_status_data, force_mavlink1=False):
                '''
                Sensirion data

                sensor_flow_data          : Sensor Corrected Flow data (type:int16_t)
                sensor_temp_data          : Sensor Temperature data (type:int16_t)
                sensor_status_data        : Sensor Status (type:int8_t)

                '''
                return self.send(self.response_sensirion_data_encode(sensor_flow_data, sensor_temp_data, sensor_status_data), force_mavlink1=force_mavlink1)

        def response_heater_control_data_encode(self, v_h, v_t, i_h, i_t, v_drop_t):
                '''
                Heater control data

                v_h                       : Heater voltage (type:float)
                v_t                       : Rt voltage (type:float)
                i_h                       : Heater current (type:float)
                i_t                       : Rt current (type:float)
                v_drop_t                  : Rt plus 160 ohm voltage (type:float)

                '''
                return MAVLink_response_heater_control_data_message(v_h, v_t, i_h, i_t, v_drop_t)

        def response_heater_control_data_send(self, v_h, v_t, i_h, i_t, v_drop_t, force_mavlink1=False):
                '''
                Heater control data

                v_h                       : Heater voltage (type:float)
                v_t                       : Rt voltage (type:float)
                i_h                       : Heater current (type:float)
                i_t                       : Rt current (type:float)
                v_drop_t                  : Rt plus 160 ohm voltage (type:float)

                '''
                return self.send(self.response_heater_control_data_encode(v_h, v_t, i_h, i_t, v_drop_t), force_mavlink1=force_mavlink1)

